# PyTorch Tensors

In [1]:
import numpy as np
import torch
torch.__version__


'1.9.0'

## Python List to Tensor

In [2]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

## Numpy ndarray to Tensor

In [3]:
arr = np.arange(1,11)

In [4]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
torch.as_tensor(arr) # shallow copy

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
torch.from_numpy(arr) # shallow copy

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
torch.tensor(arr) # deep copy 

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
torch.Tensor(arr) # deep copy to float

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [9]:
arr2d = np.arange(0.0,12.0).reshape(4,3)

In [10]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [11]:
torch.from_numpy(arr2d)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [12]:
arr = np.arange(1,11)

In [13]:
x = torch.from_numpy(arr) # shallow copy the array 

In [14]:
x2 = torch.tensor(arr) # deep copy the array

In [15]:
arr[0]=10

In [16]:
arr

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
x

tensor([10,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
x2

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Tensor 

### Placeholder Tensor

In [19]:
torch.empty(2,2) # placeholder tensor

tensor([[-4.3589e+21,  4.5597e-41],
        [ 1.6041e+16,  3.0956e-41]])

### Initialized Tensor

In [20]:
torch.zeros(2, 2) # tensor with zeros

tensor([[0., 0.],
        [0., 0.]])

In [21]:
torch.zeros(2, 2, dtype=torch.int64)

tensor([[0, 0],
        [0, 0]])

In [22]:
torch.ones(3, 3) # tensor with ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [23]:
torch.arange(0,20,2) # tensor from range

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
torch.linspace(0,20,12) # tensor from linspace

tensor([ 0.0000,  1.8182,  3.6364,  5.4545,  7.2727,  9.0909, 10.9091, 12.7273,
        14.5455, 16.3636, 18.1818, 20.0000])

In [25]:
torch.rand(4,3) # uniform distribution

tensor([[0.4560, 0.2083, 0.8946],
        [0.9723, 0.7735, 0.0359],
        [0.5749, 0.4176, 0.4604],
        [0.4593, 0.8714, 0.9970]])

In [26]:
torch.randn(4,3) # standard normal distribution

tensor([[ 0.3024, -1.1167, -1.0761],
        [ 0.2764, -0.0112, -0.5899],
        [-0.5896,  1.4845,  1.2308],
        [-0.8130, -0.2763,  0.4447]])

In [27]:
torch.randint(low=0,high=10,size=(5,5))

tensor([[3, 2, 4, 3, 4],
        [4, 8, 1, 1, 0],
        [7, 5, 2, 4, 3],
        [1, 5, 0, 8, 2],
        [4, 9, 5, 2, 6]])

In [28]:
x = torch.ones(3,3)
torch.rand_like(x) # randn_like, randint_like also exits

tensor([[0.7856, 0.1476, 0.6908],
        [0.2823, 0.2812, 0.1358],
        [0.8067, 0.6052, 0.8076]])

In [29]:
torch.manual_seed(42) # seed
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

### Reshape

In [30]:
x = torch.arange(0,20,2)
x

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
x.reshape(5,2)

tensor([[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14],
        [16, 18]])

In [32]:
x

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
x = x.reshape(5,-1) # -1 tells torch to infer the second dim

In [34]:
x

tensor([[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14],
        [16, 18]])

### Change Data Type

In [35]:
x = torch.tensor([1,2,3])

In [36]:
x

tensor([1, 2, 3])

In [37]:
x.type(torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

## Tensor Operations

In [38]:
x = torch.arange(6).reshape(3,2)

In [39]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [40]:
x[1,1]    #returns a tensor object

tensor(3)

In [41]:
x[:,1]

tensor([1, 3, 5])

In [42]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [43]:
a = torch.tensor([1.,2.,3.])

In [44]:
b = torch.tensor([4.,5.,6.])

### Element wise multiplication

In [45]:
a*b

tensor([ 4., 10., 18.])

### Dot Product

In [46]:
a.dot(b)

tensor(32.)

### Matrix multiplication

In [47]:
a = torch.tensor([[0,2,4],[1,3,5]])

In [48]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [49]:
b = torch.tensor([[6,7],[8,9],[10,11]])

In [50]:
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [51]:
a.mm(b)

tensor([[56, 62],
        [80, 89]])

In [52]:
a@b

tensor([[56, 62],
        [80, 89]])

### Euclidian normalization (magnitude)

In [53]:
x = torch.tensor([2.,3.,4.,5.])

In [54]:
x

tensor([2., 3., 4., 5.])

In [55]:
x.norm()

tensor(7.3485)

In [56]:
x.numel() # total number of elements same as len(x)

4

In [57]:
len(x)

4